// Supabase Configuration
export const SUPABASE_URL = 'https://jpqmfdgnjmfrxidzxjrz.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcW1mZGduam1mcnhpZHp4anJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMzM2MzksImV4cCI6MjA3OTYwOTYzOX0.zzKYGj-MF783XtbMjpGV-Oxj_bq4p9O-x7xj2yrMsLE';
